server:
  port: 8090
logging:
  level:
    org.springframework.web: debug
security:
  oauth2:
    client:
      client-id: provider
      client-secret: 12345
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user/me
spring:
  application:
    name: micro-oauth2-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848