server:
  port: 8091
logging:
  level:
    org.springframework.cloud.openfeign: debug
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: micro-oauth2-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848