server:
  port: 8091
logging:
  level:
    org.springframework.web: debug
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: micro-oauth2-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848