server:
  port: 8091
logging:
  level:
    org.springframework.security: debug
spring:
  application:
    name: micro-oauth2-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848